name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80a10eb724969adc93555ee9cf2ca3c9fb20a734cc9fce1b1ebb0c4f4ea8872d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
