name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.3.0_dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7946922841d7e8eba8d12115fed9c386a2ddcd8a8b7e8afbe5734133ab1d16f0"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
