name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d56e358bd96ca615d6f0bb15d0f91481c5578b1419951e7db14a933ba9a8067d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
