name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e88e3d7153c4950278155b53a074b2b2d6c84b5278c3621ac9fbb5bc32677edd"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
