name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5d04299bfe4738f973552c21668cc8bfdcd1158923abc356ae0847bc5360f5d"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
