name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d49bbaac8d4b2800ab5f97c0aa5efac0749aa1860771601cfbd408cb2b5953a"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
