name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10475cc2d005f3671c8eee9e3f7f7694924a1287373edf03e256ad70979b7f7e"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
