name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9c7b9e7b016d0d38ba4e882e721c8c1bc66d6486c9fbddaea38cbd07016582b"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
