name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93a501bc4d6fb3419095bb2469540cdfdb90907464eba1bbfb21d90353cb81a4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
