name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.3.0_dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e42bed4140e8b70baa6a51657ce919b9cc68ceecc95613adca3788caaf108bf4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
