name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23ed03791f6c303d53bd7444a5ffb5d3e02249ceb18c92d7bbea190c68713739"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
