name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8adcb10bbb5850ea70393be6a3d216358380cf5f48c8411f81ea25a15a282283"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
