name = "Lemon Pack"
author = "BlueFirePhoenix"
version = "1.3.0_dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c5c0a807630dbe99d05589523c069ced88ca4fe63f552cdb09cc93c61f41dd6"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
